### ISSUE TITLE
The q0 of quaternion become -1 periodicity

### ISSUE THREAD

**Issue by TowoC** [andres-fr/emokine#1]
I download the zip file from the website you provide.
And in the orientation.csv, the q0 of Pelvis, L3, L5, T12 become -1 periodicity.
But in the video from Stimuli/Avatar, the quaternion of torso joints seems identity since the avatar doesn't move.
Please help me, thanks.
 
And I want to know the coordinate system of emokine, is it using right hand system?
What Is the positive direction of XYZ?

**Comment by andres-fr** [comment]
Hi, thanks for trying out this project!

Unfortunately, the paper containing most explanations is still under peer review and cannot be shared. Let me see if I can try to address your questions here, please let me know otherwise. 

The CSV data is directly extracted from the MVNX data, also provided in the dataset.
MVNX is a format directly provided by the XSENS motion capture system. You can find a full specification of MVNX in this manual (PDF attached):

[MVN_User_Manual.pdf](https://github.com/andres-fr/emokine/files/13787495/MVN_User_Manual.pdf)

I encourage you to read the manual for exhaustive details.

----

> What is the coordinate system of emokine, is it using right hand system?
> What Is the positive direction of XYZ?

In section 23.4 of the manual (page 124), the coordinate system is explained.

```
By default, the earth-fixed reference co-ordinate system used is defined as a right-handed Cartesian co-ordinate system with global reference frame:
* X positive when pointing to the local magnetic North (red).
* Y according to right handed co-ordinates (West) (green).
* Z positive when pointing up (blue
```


----

> Why are some q0 values -1 while most are +1?

 I opened some `orientation.csv` file from the Emokine Dataset, and read the `Pelvis_q0` column, noticing that most values are approximately 0.99, but suddenly, some values are -0.99. I understand you are asking why is this happening. For example, we have:

```
frame_idx,ms,Pelvis_q0,Pelvis_q1,Pelvis_q2,Pelvis_q3, ...
2016,1575718892285,0.998188,-0.004516,0.045511,0.039107, ...
2017,1575718892289,-0.998188,0.004522,-0.045441,-0.039182, ...
2018,1575718892293,0.998188,-0.004524,0.045364,0.039267, ...
```
So the middle value is "flipped". **This is not a problem**.
In section 23.2.1 of the manual (page 121) "Quaternion orientation representation" is explained. Among other things, it is shown that "a quaternion is unique up to sign", such that `q = -q`. This is due to how quaternion arithmethic works. In the example above, you may notice that **not only `Pelvis_q0` is -1 in 2017, but the whole quaternion is multiplied by -1**. If you consider the equivalent quaternion,

```
2017,1575718892289,0.998188,-0.004522,0.045441,0.039182
```

You will see that it lies smoothly between 2016 and 2018.


----

Hope this helps! let me know otherwise

**Comment by TowoC** [comment]
Thanks a lot for your reply. I will read the manual for more detail information.
And thanks to you for solving my problems. I didn't notify the flipped quaternion can be flip again to the positive value.
Thanks!
